Replace NewRelic with Datadog APM
replicatedhq/krew-installer pull request #26
Opened 2022-01-08 19:29 UTC by diamonwiggins

2022-02-14 17:31 UTC, chase-replicated approved these changes
lgtm

2022-02-14 17:35 UTC, chase-replicated requested changes
lgtm but buildkite is failing due to a dependency permission issue?

2022-02-14 21:16 UTC, divolgin submitted a review, later dismissed

2022-02-22 17:45 UTC, chase-replicated approved these changes
lgtm

2022-02-22 17:58 UTC, merged